fix: Board view error fix
CNU-SW-Academy-iOS/OrderMate pull request #10
Opened 2023-04-05 07:58 UTC by cyberman0306

postStatus, createdAt
String? 으로 받도록 변경

add: 방 상태 잠금으로 변경 버튼, 함수 생성

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
ex) feat/login -> dev

### 변경 사항
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.

### 테스트 결과
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.

2023-04-05 14:41 UTC, sumin305 commented
.

2023-04-05 14:42 UTC, sumin305 commented on OrderMate/Model/UserModel.swift
> +var userModel = UserModel(username: "", password: "")
이 userModel은 방장 테스트를 위함인가요 ?

2023-04-05 14:43 UTC, sumin305 reviewed
.

2023-04-06 03:37 UTC, M1zz requested changes

2023-04-06 03:37 UTC, M1zz commented on OrderMate/Model/BoardStructModel.swift
> +    var createdAt: String? // 명세서 따른 변경, String으로 들어옴
createdAt이 nil일 수 있나요?

2023-04-06 03:37 UTC, M1zz commented on OrderMate/Model/BoardStructModel.swift
> +    var postStatus: String? // 명세서 따른 변경, String으로 들어옴
Status가 선택될 수 는 없나요?

2023-04-06 03:37 UTC, M1zz commented on OrderMate/Model/PostStatusModel.swift
> +    var directionType: String
Type은 선택지가 없나요?

2023-04-06 06:29 UTC, cyberman0306 commented on OrderMate/Model/UserModel.swift
> +var userModel = UserModel(username: "", password: "")
board host인지 확인하게 비교용 방장 ID 저장용입니다
백엔드 명세서 항목 나오면 쓰지 않을예 정입니다

2023-04-06 06:31 UTC, cyberman0306 commented on OrderMate/Model/BoardStructModel.swift
> +    var createdAt: String? // 명세서 따른 변경, String으로 들어옴
createdAt은 지금 쓰이고있지 않습니다
createdAt은 날짜 포매팅으로 사용해야 해서
이슈 새로 팠습니다

2023-04-06 06:32 UTC, cyberman0306 commented on OrderMate/Model/BoardStructModel.swift
> +    var postStatus: String? // 명세서 따른 변경, String으로 들어옴
postStatus는 방장이 선택할수있게 기능 추가예정입니다

2023-04-06 06:32 UTC, cyberman0306 commented on OrderMate/Model/PostStatusModel.swift
> +    var directionType: String
type는 next, prev의 선택지가 있습니다

2023-04-06 08:14 UTC, MoonGoon72 approved these changes
CreatedAt을 String으로 받아올지 Date로 받아올 지 얘기를 해봐도 좋을 것 같아요! 백엔드에서 String으로 해놨다고 바꾸기보단 어떤 게 더 좋을지 이야기해보고 정하면 좋지 않을까요?
코드 잘 봤습니다 :)

2023-04-06 14:23 UTC, closed without merging

2023-04-06 14:43 UTC, M1zz commented on OrderMate/Model/BoardStructModel.swift
> +    var postStatus: String? // 명세서 따른 변경, String으로 들어옴
제 말은 enum으로 만들 수는 없었는가 입니다